# Generated by Django 4.0.6 on 2022-08-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('merk', models.CharField(max_length=100)),
                ('plat', models.IntegerField()),
                ('telp', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=100)),
            ],
            options={
                'db_table': 'motor',
            },
        ),
    ]
