# Generated by Django 4.0.6 on 2022-08-04 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='econtact',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='eemail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='ename',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='eid',
        ),
    ]
