# Generated by Django 4.0.6 on 2022-08-05 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_tamus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tamus',
        ),
        migrations.RenameField(
            model_name='tamu',
            old_name='nama',
            new_name='name',
        ),
    ]
