# Generated by Django 4.0.6 on 2022-08-05 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_delete_tamus_rename_nama_tamu_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyawan',
            name='jenisKelamin',
            field=models.CharField(choices=[('Pria', 'Pria'), ('Wanita', 'Wanita')], default='Pria', max_length=10),
        ),
    ]
