# Generated by Django 4.0.6 on 2022-08-06 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_karyawan_jeniskelamin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyawan',
            name='divisi',
            field=models.CharField(choices=[(('IT',), ('IT',)), ('PEMASARAN', 'PEMASARAN')], default=('IT',), max_length=20),
        ),
    ]
