# Generated by Django 4.0.6 on 2022-08-06 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_alter_karyawan_divisi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyawan',
            name='divisi',
            field=models.CharField(choices=[('IT', 'IT'), ('PEMASARAN', 'PEMASARAN'), ('PRODUKSI', 'PRODUKSI')], default='IT', max_length=20),
        ),
        migrations.AlterField(
            model_name='tamu',
            name='foto',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
