# Generated by Django 4.0.6 on 2022-08-25 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_alter_karyawan_divisi_alter_tamu_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='karyawan',
            options={'verbose_name': "Employee'"},
        ),
        migrations.AlterModelOptions(
            name='tamu',
            options={'verbose_name': "Guest'"},
        ),
        migrations.AlterField(
            model_name='tamu',
            name='foto',
            field=models.ImageField(default=False, null=True, upload_to=''),
        ),
    ]
