# Generated by Django 4.0.6 on 2022-08-28 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_alter_karyawan_options_alter_tamu_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tamu',
            options={'verbose_name': 'Guest'},
        ),
        migrations.AlterField(
            model_name='tamu',
            name='karyawan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.karyawan'),
        ),
    ]
