# Generated by Django 4.0.6 on 2022-08-28 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_alter_tamu_karyawan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tamu',
        ),
    ]
