# Generated by Django 4.0.6 on 2022-08-28 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_delete_tamu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tamu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('namaIntansi', models.CharField(max_length=100)),
                ('jaminan', models.CharField(max_length=100)),
                ('keperluan', models.CharField(max_length=100)),
                ('jumlahTamu', models.IntegerField()),
                ('foto', models.ImageField(default=False, null=True, upload_to='')),
                ('waktu', models.DateTimeField(auto_now_add=True)),
                ('karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.karyawan', verbose_name='karyawan_id')),
            ],
            options={
                'verbose_name': 'Guest',
                'db_table': 'tamu',
            },
        ),
    ]
