# Generated by Django 4.0.6 on 2022-08-31 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.IntegerField()),
                ('nama', models.CharField(max_length=255)),
                ('hobi', models.CharField(max_length=255)),
                ('alamat', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'mahasiswa',
            },
        ),
    ]
